import type { Metadata } from 'next';
import Header from '../../public/globals/header';
import '../../public/globals/styles/global.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Betsell',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className='Container'>
          <Header></Header>
        </div>{children}
      </body>
    </html>
  )
}
